driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: fedora-23
  - name: debian-7.10
    run_list:
      - recipe[apt]
  - name: debian-8.4
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-15.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-15.10
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[librato::default]
      - recipe[librato::apache]
    attributes:
      librato:
        apache:
          path: '/test-status'
