driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: fedora-23
  - name: amazonlinux-2016.03
    driver:
      name: ec2
      image_id: ami-7172b611
      aws_ssh_key_id: test-kitchen
      region: us-west-2
      availability_zone: a
      require_chef_omnibus: true
      instance_type: t2.large
      associate_public_ip: true
      interface: dns
    transport:
      username: ec2-user
      ssh_key: ~/.ssh/id_rsa
  - name: debian-7.10
    run_list:
      - recipe[apt]
  - name: debian-8.4
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-15.04
    run_list:
      - recipe[apt]
  - name: ubuntu-15.10
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[librato::default]
      - recipe[librato::apache]
      - recipe[librato::elasticsearch]
      - recipe[librato::jvm]
      - recipe[librato::mongodb]
      - recipe[librato::nginx]
      - recipe[librato::nginx_plus]
      - recipe[librato::postgresql]
      - recipe[librato::mysql]
      - recipe[librato::zookeeper]
      - recipe[librato::docker]
      - recipe[librato::haproxy]
      - recipe[librato::memcached]
      - recipe[librato::redis]
      - recipe[librato::varnish]
    attributes:
      librato:
        email: 'foo@bar.baz'
        token: '1234abcd'
        logging:
          use_log_file: true
        elasticsearch:
        jvm:
        mongodb:
          databases: ['foo', 'bar', 'baz']
        nginx:
          path: '/test-status'
        nginx_plus:
          path: '/test-status'
        postgresql:
          databases: [
            {
              name: 'mydb',
              instance: 'baz',
              host: 'localhost',
              port: 5432,
              user: 'foo',
              password: 'baz',
            }
          ]
        mysql:
          databases: [
            {
              name: 'mydb',
              host: 'localhost',
              port: 3306,
              user: 'foo',
              password: 'baz',
              innodb_stats: true,
            }
          ]
        zookeeper:
        docker:
        haproxy:
        memcached:
        redis:
        varnish:
        apache:
          path: '/test-status'
